# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0 //2
/run/verbose 0 //2
/event/verbose 0
/tracking/verbose 0 //1
/control/execute vis.mac
#/control/execute particle.mac
/gps/verbose 0
#/gps/source/add 1
/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 0 0 -50 cm
/gps/direction 0 0 1
/gps/ene/type Mono
/gps/ene/mono 2.09 MeV
#/gps/ene/min 0 MeV
#/gps/ene/max 10 MeV
#/gps/ene/gradient 1
#/gps/ene/intercept 0
/run/beamOn 50000
#/run/beamOn 50000
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/beamOn 5
# 
# proton 210 MeV to the direction (0.,0.,1.)
#
#/gun/particle proton
#/gun/energy 210 MeV
#/tracking/verbose 2
#
#/run/beamOn 1

